### ISSUE TITLE
Mobile touch iOS

### ISSUE THREAD

**Issue by atadioli** [jestrux/jquery-mini-event-calendar#18]
Hi Walter,
I have another problem. The link (the button) on the day onto the calendar on safari/iphone don't work!
Why? Have you an idea?
Other user have the same problem?

Thank you very much.

**Comment by jestrux** [comment]
Hey there, can you please take a screenshot and mark it?

**Comment by atadioli** [comment]
Hi,
Simply don't click. I tried changing the tag button with the tag a but it doesn't change.
This only on Safari or Chrome ON IOS.
I pushed rou script here: http://vpn.seidigitale.net/mec/example.html

Thank you!

**Comment by jestrux** [comment]
Hi @atadioli 

I just pushed an update that fixes this issue.

Could you please test again to make sure that it now works properly? 

PS: I had to make some few style changes to fix this issue, so you might have to modify your styles too.
