### ISSUE TITLE
Multiple events on 1 day

### ISSUE THREAD

**Issue by tvnweb** [jestrux/jquery-mini-event-calendar#2]
If more than 1 event occurs in the same day, only first is putted on data-event attribute.

**Comment by jestrux** [comment]
Hey man, thanks for checking this out. I've been trying to figure this out UXwise myself. Any ideas?

**Comment by tvnweb** [comment]
Maybe you could use an ID on data-event that refers to an array (JSON) with events list

**Comment by jestrux** [comment]
Okay, so I wasn't too concerned with the implementation part; I figured that wouldn't be too hard.

I was thinking along the lines of what the user sees in case of multiple events, whether I should show multiple dots and in that  what happens if there are like 10 events on the same days do I show dots for all events. 

Also what happens when a user clicks an day with multiple events, do I display them both.

Also the link button, how would it behave in case of these multiple events.

**Comment by ilswj** [comment]
Hello, thanks for the hard work you've done,
i have the same problem here, i need to display multiple events in calTFooter when they occure in the same day. and when no date is selected, it displays all events.

**Comment by jestrux** [comment]
Hey @ilswj concerning the first part of showing all events in a day, I'm still not sure how to show all events and still keep it minimal. 

The idea I have right now is to maybe show something like `2 Events` in case of two events and so on.....Would that work for you? 

Or if you have a different idea you could share it too.

Concerning the second part, I'm not completely sure what you mean by '*when no date is selected show all events*', could you elaborate?

**Comment by premy** [comment]
Maybe an idea would be to check on click if the day has more than 1 event, in which case the user sees something like 'Multiple events for this day. Please click to see'

**Comment by jestrux** [comment]
@premy You have an idea similar to mine, but the issue is:
1. How do we indicate that this day has multiple events?
2. What happens when a user 'clicks to see' on a day with multiple events without compromising the simplicity too much?

**Comment by premy** [comment]
Well I'd say you just leave the indication to show as is, as if there was only 1 event. When the user clicks to see what event there is, then he will see the message 'Multiple events for this day. Please click to see'.
It's up to the developper to show a page where all events for that day is listed when the user clicks on 'Multiple events for this day. Please click to see'.

db_events will then look something like this:

var db_events = [
...
{
`title: "<a href='/events240918'>Multiple events for this day. Please click to see</a>",`
date: 1532381440036,
link: "/events240918"
},
...
];

**Comment by jestrux** [comment]
@premy @ilswj @tvnweb Hey guys, sorry I was away from this for a bit.

I think I've found a solution of how to implement this without compromising the 'mini-ness' of the mini calendar.

1. *Event Links*
- Like @premy suggested above, a developer can optionally provide a link to the event and even provide a `linkOutside` option to show the link outside the current site

2. *Preview On Event(s) Hover*
- I was thinking when a user hovers over the event at the bottom, show a popover that shows summarized information about the event like time and place.
- If there's a link provided add a `view event` link
- I'm thinking for this to happen, a developer needs to explicitly allow the feature using something like `hover_preview`.

3. *Multiple Events*
- For days with multiple events, I think the message at the bottom should show ${n} events on this day, then when a user hovers over the message, it'll show the events

I would really love to hear what you guys think about this.

**Comment by tobymansfieldcreative** [comment]
Hi @jestrux - I've just found your calendar and I love it, but I'm a bit of a JS novice (sorry in advance).

How can I modify the code to list all of the events on a single day in #calTFooter instead of the solutions above? I think I need an .each function instead of just changing the content of the html (?) but I'm not bright enough to work it out!
