### ISSUE TITLE
Does not work on safari (iPhone)

### ISSUE THREAD

**Issue by premy** [jestrux/jquery-mini-event-calendar#22]
If you try opening http://sistemauniverso.com.br/caltest.aspx on iPhone you get a blank screen. Added your latest .css and .js file

**Comment by jestrux** [comment]
What version of iOS are you using? I just tested it on Safari on iOS 12.2 and it works just fine.

**Comment by jestrux** [comment]
@premy What version of iOS are you using? I just open the link you sent on Safari on iOS 12.2 and it works just fine.

**Comment by premy** [comment]
Ok, I'm still using my good ole iPhone 4, so stuck on iOS 7.1.2. Never saw any reason to get a new phone, maybe now ;-)

**Comment by jestrux** [comment]
Haha, you shouldn't have to.....was it working with the old CSS?

**Comment by premy** [comment]
Sorry being a bit late. No, the old CSS did not work, that's when I thought I'd try it with the newest version. Probably not worth your time anyhow, for I guess it works for the majority of devices today.

**Comment by jestrux** [comment]
I would work on it but I just don't have an iPhone 4 to test and see the error on so I wouldn't know where to start.
