### ISSUE TITLE
Edge browser, dates sorting

### ISSUE THREAD

**Issue by janvrska** [jestrux/jquery-mini-event-calendar#24]
I find out that the calendar dont work correctly on edge. date fields dont match days of the week ( you can also see sunday on the next row) 
![screen](https://user-images.githubusercontent.com/1644599/64203605-230c4880-ce94-11e9-9e97-360b31b50ff2.PNG)

**Comment by jestrux** [comment]
Hey @janvrska thank you for reporting this, sorry I saw it a bit late. I'll get back to you after I've tested it out to see what's the problem.
