### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by ibrahimkonushefci** [jestrux/jquery-mini-event-calendar#25]
Is there any options to change the date format?
For example instead of 2020-02-13 I prefer to use 13-02-2020

**Comment by jestrux** [comment]
Hi @ibrakunushefci 

Currently there is no such option but if you tell me your use case I can see how to help.

**Comment by ibrahimkonushefci** [comment]
Thank you for your reply,

If I would like to add an event for today, I would have to write the date like this: 2020-02-14
Instead, how can I change the format so it would be acceptable if I write 14-02-2020 (European format)

Here is some of your code that I am not sure what to change:
`var today = new Date();
var curMonth = today.getMonth();
var curYear = today.getFullYear();`

`var ldate = new Date(year, month);
var dt = new Date(ldate);
var weekDay = dt.getDay();`

**Comment by jestrux** [comment]
Ooh okay, so what you're saying is the event dates on your server are stored using european format and when you bring them to the frontend they don't work with the library because it expects a different date format.

**Comment by ibrahimkonushefci** [comment]
Yes, that's exactly what I'm saying.
My client wants me to change the format, so when he types the date (e.g. 14-02-2020), he wants the event to be displayed for today.

What do I need to change in your library so it would accept only european format?

**Comment by jestrux** [comment]
Okay, if you're sure all your dates will come in as strings formatted in european format, the piece you need to change is around line **111** on `mini-event.calendar.js`.

The current version is like this:

```javascript
var eventIndex = settings.events.findIndex(function(ev) {
	return areSameDate(dt, new Date(ev.date));
});
```

Just change that to:

```javascript
var eventIndex = settings.events.findIndex(function(ev) {
	// split date string with - to get your date in europe format as array
	var [month, day, year] = ev.date.split("-");
	// recreate the date using the us format
	ev.date = new Date(`${day} ${month} ${year}`);
	
	return areSameDate(dt, new Date(ev.date));
});
```

**Comment by ibrahimkonushefci** [comment]
Unfortunately, when I try to replace the given code, this is the result I get
https://imgur.com/U4YTD4n

**Comment by jestrux** [comment]
Okay, could you show me a sample of the data you're using?

**Comment by ibrahimkonushefci** [comment]
This is the sample of the data I am using:
```
var plannedEvents = [{
     title: "SEECP Event",
     date: '18-02-2020',
     location: 'Prishtina',
     link: "http://seecp.mfa-ks.net/eventi-single/58"
}];
	
$(document).ready(function () {
     $("#calendar2").MEC({
	 events: plannedEvents
     });
});
```

And on the `mini-event-calendar.js` all I have changed is the line 111-113 with your provided code

**Comment by jestrux** [comment]
Oh there was a problem with the code I sent, it was still expecting the string to be in American format.

Here's the correct version

```javascript
var eventIndex = settings.events.findIndex(function(ev) {
	// split date string with - to get your date in europe format as an array
	const [day, month, year] = ev.date.split("-");
	// recreate the date using the us format
	ev.date = new Date(`${month} ${day} ${year}`);
	
	return areSameDate(dt, new Date(ev.date));
});
```

By the way if you're expecting your clients to not have the latest evergreen browsers that ship with the latest ES6 features, you can tweak it to this 👇 ...It's basicaly the same thing just a bit longer.

```javascript
var eventIndex = settings.events.findIndex(function(ev) {
	// split date string with - to get your date in europe format as an array
	var euroDateArray = ev.date.split("-");

	// recreate the date using the us format
	var euroDateDay = euroDateArray[0];
	var euroDateMonth = euroDateArray[1];
	var euroDateYear = euroDateArray[2];
	ev.date = new Date(euroDateMonth + " " + euroDateDay + " " + euroDateYear);
	
	return areSameDate(dt, new Date(ev.date));
});
```
