### ISSUE TITLE
Not an issue. Year view of calendar instead of Month

### ISSUE THREAD

**Issue by sarvajeetvishwakarma** [jestrux/jquery-mini-event-calendar#26]
Hi @jestrux ,
I have a request, is it possible to view the calendar in yearly view, like instead of one month can we see all months? and changing the arrows on top will change entire year? Similar to this: https://prnt.sc/03vu7Te_qE4R

**Comment by jestrux** [comment]
Hey, just saw your issue now. Sadly having a year view goes beyond the scope of a "mini" calendar.
