### ISSUE TITLE
Multiple days

### ISSUE THREAD

**Issue by goncaloc95** [jestrux/jquery-mini-event-calendar#3]
Hi,

How can i add a start and a end date for an event and show multiple days on calendar ?

**Comment by jestrux** [comment]
Hey @goncaloc95 how did you manage this?

**Comment by goncaloc95** [comment]
Hey @jesstrux ,

To do that i did a foreach with the query results and then checked the events that had an end date which means that the events has more then one day. Then i did a while loop to add each day to the array.

Did I made myself clear or do you want to see my code ?

**Comment by jestrux** [comment]
@goncaloc95 Oh okay, sounds like what I would have done. Do you want to maybe add support for that particular implementation to the main library and create a pull request?

**Comment by jestrux** [comment]
Although we should maybe find a way to indicate that it's a continuing event without going to far from the *mini* part of the library.

PS: Could you reopen the issue till we resolve this.
