### ISSUE TITLE
Add theming options

### ISSUE THREAD

**Issue by jestrux** [jestrux/jquery-mini-event-calendar#4]
Add alternate default themes for the calendar and options to customize colors e.g background-color, accent-color.

**Comment by jestrux** [comment]
@atadioli  I really love the UI customizations you made to the plugin to fit your theme, I almost didn't recognize at first😄 

If it's not a confidential project, can I see how the calendar looks in your UI? 

I want to work on some theming options for the plugin, so I'm looking for some variation of usage so I can make as many options as possible easy to customize.

**Comment by atadioli** [comment]
Yes, no problem! I send you a private message with the link of the project.
;-)
