### ISSUE TITLE
Loading events for current month

### ISSUE THREAD

**Issue by premy** [jestrux/jquery-mini-event-calendar#6]
Hi mate, this not really an issue I guess, but maybe you can help me out.
I'm loading events thru ajax call like this:
``` javascript
function getEventos(m, y) {
    var obj = {};
    obj.mes = m;
    obj.ano =y;
    $.ajax({
        type: "POST",
        url: "caltest.aspx/GetEventos",
        data: JSON.stringify(obj),
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: OnSuccess,
        failure: function (response) {
            alert(response.responseText);
        },
        error: function (response) {
            alert(response.responseText);
        }
    });
}

var db_events = [];
function OnSuccess(response) {   
    var evento = response.d; 
  evento = $.parseJSON(evento);
  evento.forEach(function (evt) {
      db_events.push({ date: new Date(evt.date).getTime(), title: evt.title, link: evt.link });
  });
  return db_events;
}
```

Then I call it inside populateCalendar like this:
```javascript
function populateCalendar(month, year) {
            getEventos(month, year);
            tbody.html("");
...
}
```

Everything works fine except events for current month do not show on pageload. When I navigate to other months, the events show up as expected and when I navigate back to the current month, then the events do show up.
Hope u can help me figure out a solution.

**Comment by jestrux** [comment]
Hey man @premy, sorry I sort of left this unattended for a while. I'm playing catch up now. Were you able to find a solution or do you still need help with this?

**Comment by premy** [comment]
Well, better late than never ;-), thanks!. Sorry I didn't spot this response earlier. But anyways, I ended up not using your calendar and chose for a more traditional calendar. But I'd still prefer using your calendar if I get it working as I need it to.

**Comment by jestrux** [comment]
@premy Hey man, thanks for reaching back, is there like a test server I can use to fetch events while testing out a solution for you idea?

**Comment by premy** [comment]
Thank u for trying to help out. Hope to learn some more about js along the way. Well, here you go: sistemauniverso.com.br/caltest.aspx. I also attached an image of the test data returned by the ajax call.
So please allow me to summarize what's not working as I'd like it to:
1. Current and next month events do not get selected when the page loads (here april and may). They only get selected when I go to previous or next month and then come back.
2. When a range is selected as in march 1-3 (pls see the testdata), I would like to show **March 1 - March 3** when either of the 3 days in the range is clicked, but so far I just manage to show the last day (March 3).
![calevents](https://user-images.githubusercontent.com/1387407/56062432-bbb5f680-5d42-11e9-9060-654d1ba17d3d.gif)

**Comment by premy** [comment]
Hello pal, I also set up a webapi, which returns json in case you prefer:
http://sistemauniverso.com.br/api/CalApi/GetEvents/?id=4&ano=2019
id takes month as parameter and ano takes year parameter.
Thank u.

**Comment by jestrux** [comment]
Hello again @premy, thanks for the api. I used it to come up with a solution to your problem.

To use this solution, please download the latest version of the plugin because I had to make a few changes that are required by this solution.

In quick recap, what I did was: 

   1. Initialize plugin
   1. Listen for onMonthChanged event
   1. Add loading class to calendar which will prevent user from clicking till calendar is loaded
   1. Fetch events from the API you provided
   1. For each event, find an item in the calendar that has the same date as event date
   1. Add event class and data-event attribute to that date item
   1. Remove loading class from calendar

Here is the code:

A bit of CSS to show 'loading' text on top of the calendar if it has a class off 'loading'

```css
#calendar{
	position: relative;
}

#calendar.loading:after{
	content: 'LOADING...';
	position: absolute;
	top: 0;
	bottom: 0;
	left: 0;
	right: 0;
	background: rgba(34, 37, 46, 0.88);
	color: #fffc23;
	display: flex;
	align-items: center;
	justify-content: center;
	letter-spacing: 0.3em;
}
```

And the javascript
```javascript
var calendar;
$(document).ready(function(){
	calendar = $("#calendar");
	
	$("#calendar").MEC({
		onMonthChanged: function(month, year){
			// month indexes start at 0
			var actualMonth = month + 1;

			getEventos(actualMonth, year, function(events) {
				var calFooter = $("#calTFooter");
				if(events.length){
					// Footer that's hidden by default when there are no events provided
					calFooter.css("display", "flex");
				}else{
					calFooter.css("display", "none");
				}

				events.forEach(function(event){
					var date = new Date(event.date).getDate();
					var element = $(".a-date").filter(function() {
						var text = $(this).text();
						text.trim();
						var sameDate = parseInt(text) === date;
						var fromPastOrNextMonth = $(this).hasClass('blurred');

						return sameDate && !fromPastOrNextMonth;
					});
					element.addClass('event').attr('data-event', JSON.stringify(event));
				});
			});
		}
	});
});

function getEventos(month, year, callback) {
	var events_url = "http://sistemauniverso.com.br/api/CalApi/GetEvents/";
	events_url += "?id=" + month;
	events_url += "&ano="+ year;

	// quick work around for CORS issue
	events_url = 'https://cors-anywhere.herokuapp.com/' + events_url;

	$.getJSON(events_url, callback)
}
```

**Comment by premy** [comment]
Thanks a lot, will try it out and let you know. Would really be cool if I get it working for it looks very nice and is super light.

**Comment by jestrux** [comment]
@premy Of course man, please do tell me how it goes, because once it works there is one more tweak I want to suggest that will ensure that you don't fetch events for the same month twice.

**Comment by premy** [comment]
Ok, finally had a chance to check it out and it works perfectly, thanks a lot. Only thing, being an aspx page all clicks would trigger a postback, as I had pointed out in another post here. But adding e.preventDefault(); on the following two functions takes care of that.
`miniCalendar.on("click touchstart", ".a-date", function(e){
       e.preventDefault(); 
...
mover.bind("click", function(e){
            e.preventDefault(); 
`

**Comment by jestrux** [comment]
@premy Oh nice, thanks for pointing that out, I'll update the main library and add in the **preventDefault();** calls. I'm glad it worked out for you.
